version: '3'

services:
  kafka1:
    image: "confluentinc/cp-enterprise-kafka:latest"
    container_name: kafka1
    ports:
      - '9092:9092'
      - '29092:29092'
      - '29093:29093'
    volumes:
      - $PWD/kafka_1/data:/var/lib/kafka/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_LOCAL_HOST:PLAINTEXT,PLAINTEXT_EXTERNAL_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_LOCAL_HOST://localhost:29092,PLAINTEXT_EXTERNAL_HOST://192.168.5.254:29093
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 'r1'

networks:
  default:
    name: k_cluster_net
    external: true
