version: '3'

services:
  kafka2:
    image: "confluentinc/cp-enterprise-kafka:latest"
    container_name: kafka2
    ports:
      - '9093:9092'
      - '29094:29092'
      - '29095:29093'
    volumes:
      - $PWD/kafka_2/data:/var/lib/kafka/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_LOCAL_HOST:PLAINTEXT,PLAINTEXT_EXTERNAL_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_LOCAL_HOST://localhost:29094,PLAINTEXT_EXTERNAL_HOST://192.168.5.254:29095
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: 'r1'

networks:
  default:
    name: k_cluster_net
    external: true
